apiVersion: v1
kind: Service
metadata:
  name: client-gateway
  labels:
    service: client-gateway
spec:
  selector:
    app: client-gateway
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
  labels:
    service: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.client_gateway.image.name }}:{{ .Values.client_gateway.image.tag }}
          env:
            {{- with .Values.client_gateway }}
            - name: SAFE_CONFIG_BASE_URI
              value: "https://config-v2.smr.network"
            - name: APPLICATION_PORT
              value: "3000"
            - name: REDIS_HOST
              value: redis-master
            - name: PRICES_PROVIDER_API_KEY
              value: {{ .exchange_api.key | quote }}
            - name: AUTH_TOKEN
              value: "12345"
            - name: ALERTS_PROVIDER_SIGNING_KEY
              value: "12345"
            - name: ALERTS_PROVIDER_API_KEY
              value: "12345"
            - name: ALERTS_PROVIDER_ACCOUNT
              value: "12345"
            - name: ALERTS_PROVIDER_PROJECT
              value: "12345"
            - name: EMAIL_API_APPLICATION_CODE
              value: "12345"
            - name: EMAIL_API_FROM_EMAIL
              value: "servrox@servrox.solutions"
            - name: EMAIL_API_KEY
              value: "12345"
            - name: EMAIL_TEMPLATE_RECOVERY_TX
              value: "12345"
            - name: EMAIL_TEMPLATE_UNKNOWN_RECOVERY_TX
              value: "12345"
            - name: EMAIL_TEMPLATE_VERIFICATION_CODE
              value: "12345"
            - name: JWT_ISSUER
              value: "12345"
            - name: JWT_TOKEN
              value: "12345"
            - name: INFURA_API_KEY
              value: "12345"
            - name: PUSH_NOTIFICATIONS_API_PROJECT
              value: "12345"
            - name: PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_CLIENT_EMAIL
              value: servrox@servrox.solutions
            - name: PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_PRIVATE_KEY
              value: "12345"
            - name: RELAY_PROVIDER_API_KEY_ARBITRUM_ONE
              value: ""
            - name: RELAY_PROVIDER_API_KEY_BLAST
              value: ""
            - name: RELAY_PROVIDER_API_KEY_GNOSIS_CHAIN
              value: ""
            - name: RELAY_PROVIDER_API_KEY_SEPOLIA
              value: ""
            {{- end }}
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          ports:
            - name: http
              containerPort: 3000


---
apiVersion: v1
kind: Secret
metadata:
  name: client-gateway
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "client-gateway") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $rocketSecretKey := (get $secretData "rocket-secret-key") | default (randAlphaNum 44 | b64enc | b64enc) }}
  rocket-secret-key: {{ $rocketSecretKey | quote }}
  {{- $webhookToken := (get $secretData "webhook-token") | default (randAlphaNum 44 | b64enc) }}
  webhook-token: {{ $webhookToken | quote }}
