apiVersion: v1
kind: Service
metadata:
  name: transaction
  labels:
    service: transaction
spec:
  selector:
    app: transaction
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  labels:
    service: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      annotations:
        # enforce pod restart when nginx config changes
        checksum/proxy-config: {{ .Files.Get "files/transaction-service/nginx/nginx.conf" | sha256sum }}
      labels:
        app: transaction
    spec:
      initContainers:
        - name: db-create
          image: {{ include "safe.postgresql-util-image" . }}
          command: [ bash ]
          args:
            - -c
            - |
              while ! pg_isready; do
                echo waiting for postgres to become ready
                sleep 1
              done
              createdb transaction_service || true
          env:
            - name: PGHOST
              value: postgresql
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
      containers:
        - name: django
          image: {{ .Values.transaction_service.image.name }}:{{ .Values.transaction_service.image.tag }}
          command: [bash]
          args:
            - -c
            - |
              {{ .Files.Get "files/transaction-service/web/run_web.sh" | nindent 14 }}
          env:
            {{- with .Values.transaction_service }}
            - name: ETHEREUM_NODE_URL
              value: {{ .etherium.node_url | quote }}
            - name: ETHEREUM_TRACING_NODE_URL
              value: {{ .etherium.tracing_node_url | quote }}
            - name: ETH_L2_NETWORK
              value: {{ .etherium.l2_network | quote }}
            - name: PYTHONPATH
              value: /app/
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.production
            - name: DEBUG
              value: {{ .django.debug | quote }}
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_NAME
              value: transaction_service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_NAME)
            - name: REDIS_URL
              value: redis://$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)/1
            - name: RABBITMQ_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: rabbitmq
                   key: rabbitmq-password
            - name: CELERY_BROKER_URL
              value: amqp://admin:$(RABBITMQ_PASSWORD)@$(RABBITMQ_SERVICE_HOST)/
            - name: GUNICORN_BIND_SOCKET
              value: "unix:/gunicorn/gunicorn.socket"
            - name: GUNICORN_BIND_PORT
              value: "8000"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: transaction-service
                  key: secret-key
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # allow pod ip for readiness probes
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ join "," (list .hostname "$(POD_IP)") }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .django.superuser.username | quote }}
            - name: DJANGO_SUPERUSER_EMAIL
              value: {{ .django.superuser.email | quote }}
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-service
                  key: django-superuser-password
            - name: CSRF_TRUSTED_ORIGINS
              value: {{ print "https://" .hostname | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 200m
              memory: 900Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - name: staticfiles
              mountPath: /nginx
            - name: gunicorn
              mountPath: /gunicorn

        - name: nginx
          image: nginx:stable-alpine3.17
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DOCKER_NGINX_VOLUME_ROOT
              value: /www
            - name: GUNICORN_BIND_SOCKET
              value: unix:/gunicorn/gunicorn.socket
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: staticfiles
              mountPath: /nginx
            - name: gunicorn
              mountPath: /gunicorn
          readinessProbe:
            httpGet:
              path: /api/v1/about/
              port: http
            initialDelaySeconds: 15
      volumes:
        - name: nginx-config
          configMap:
            name: transaction-service-nginx
        - name: staticfiles
          emptyDir: {}
        - name: gunicorn
          emptyDir: {}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-nginx
  labels:
    app: transaction
data:
  nginx.conf: |-
    {{ .Files.Get "files/transaction-service/nginx/nginx.conf" | nindent 4 }}


---
apiVersion: v1
kind: Secret
metadata:
  name: transaction-service
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "transaction-service") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secret-key") | default (randAlphaNum 128 | b64enc) }}
  secret-key: {{ $secretKey | quote }}
  {{- $djangoSuperuserPassword := (get $secretData "django-superuser-password") | default (randAlphaNum 32 | b64enc) }}
  django-superuser-password: {{ $djangoSuperuserPassword | quote }}
