#apiVersion: v1
#kind: Service
#metadata:
#  name: web-core
#  labels:
#    service: web-core
#spec:
#  selector:
#    app: web-core
#  ports:
#    - name: http
#      port: 8080
#      protocol: TCP
#      targetPort: http
#
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: web-core
#  labels:
#    service: web-core
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: web-core
#  template:
#    metadata:
#      labels:
#        app: web-core
#    spec:
#      containers:
#        - name: node
#          image: {{ .Values.web_core.image.name }}:{{ .Values.web_core.image.tag }}
#          env:
#            {{- with .Values.web_core }}
#            - name: NEXT_PUBLIC_INFURA_TOKEN
#              valueFrom:
#                secretKeyRef:
#                  name: web-core
#                  key: infura-token
#            - name: NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN
#              valueFrom:
#                secretKeyRef:
#                  name: web-core
#                  key: safe-apps-infura-token
#            ## CGW
#            - name: NEXT_PUBLIC_GATEWAY_URL_PRODUCTION
#              value: https://{{ $.Values.client_gateway.hostname }}
#            - name: NEXT_PUBLIC_GATEWAY_URL_STAGING
#              value: https://{{ $.Values.client_gateway.hostname }}
#              # Transaction simulation
#            - name: NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL
#              value: ""
#            - name: NEXT_PUBLIC_TENDERLY_PROJECT_NAME
#              value: ""
#            - name: NEXT_PUBLIC_TENDERLY_ORG_NAME
#              value: ""
#            - name: NEXT_PUBLIC_IS_PRODUCTION
#              value: "true"
#            - name: NEXT_PUBLIC_SAFE_VERSION
#              value: ""
#            - name: NEXT_PUBLIC_SENTRY_DSN
#              value: ""
#            - name: NEXT_PUBLIC_BEAMER_ID
#              value: ""
#            - name: NEXT_PUBLIC_WC_BRIDGE
#              value: {{ .wc_bridge | quote }}
#            {{- end }}
#          resources:
#            requests:
#              cpu: 100m
#              memory: 100Mi
#            # allow spiking because container builds app on startup...
#            # build seems to be quite hungry
#            limits:
#              cpu: 2000m
#              memory: 3000Mi
#          ports:
#            - name: http
#              containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
#            initialDelaySeconds: 5
#
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: web-core
#stringData:
#  infura-token: {{ .Values.web_core.infura_token | quote }}
#  safe-apps-infura-token: {{ .Values.web_core.safe_apps_infura_token | quote }}
