version: "3.9"

volumes:
  nginx-shared:

services:
  config-nginx:
    image: nginx:1.20-alpine
    env_file:
      - ./safe-config-service/.dev.env
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"
    volumes:
      - ./safe-config-service/nginx/templates:/etc/nginx/templates
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT-/nginx}
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    env_file:
      - ./safe-config-service/.dev.env
    volumes:
      - ./safe-config-service/data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  web:
    build: ./safe-config-service/
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT:-/nginx}
    env_file:
      - ./safe-config-service/.dev.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  # safe-client-gateway services
  nginx:
    image: nginx:1.21-alpine
    env_file:
      - ./safe-client-gateway/.dev.env
    ports:
      - "${NGINX_HOST_PORT:-8090}:80"
    volumes:
      - ./safe-client-gateway/nginx/templates:/etc/nginx/templates
    depends_on:
      - gateway-web

  gateway-web:
    build: ./safe-client-gateway/
    env_file:
      - ./safe-client-gateway/.dev.env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    env_file:
      - ./safe-client-gateway/.dev.env
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    depends_on:
      - web

  # web-core
  ui:
    build: ./web-core/
    env_file:
      - ./web-core/.env.example
    ports:
      - "3000:3000"
