version: "3.9"

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.20-alpine
    env_file:
      - ./safe-config-service/.dev.env
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"
    volumes:
      - ./safe-config-service/nginx/templates:/etc/nginx/templates
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT-/nginx}
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    env_file:
      - ./safe-config-service/.dev.env
    volumes:
      - ./safe-config-service/data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  web:
    build: ./safe-config-service/
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT:-/nginx}
    env_file:
      - ./safe-config-service/.dev.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
