version: '3.9'

services:
  nginx:
    image: nginx:1.21-alpine
    env_file:
      - .dev.env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - web

  web:
    build: .
    env_file:
      - .dev.env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    env_file:
      - .dev.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
