apiVersion: v2
name: safe
version: 0.1.0
dependencies:
  - name: postgresql
    version: "12.2.6"
    repository: "https://charts.bitnami.com/bitnami"
  - name: redis
    version: 17.9.3
    repository: "https://charts.bitnami.com/bitnami"
  - name: rabbitmq
    version: 11.13.0
    repository: "https://charts.bitnami.com/bitnami"
