apiVersion: v1
kind: Service
metadata:
  name: transaction-web
  labels:
    service: transaction-web
spec:
  selector:
    app: transaction-web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-web
  labels:
    service: transaction-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-web
  template:
    metadata:
      annotations:
        # enforce pod restart when nginx config changes
        checksum/proxy-config: {{ .Files.Get "files/transaction-service/nginx/nginx.conf" | sha256sum }}
      labels:
        app: transaction-web
    spec:
      initContainers:
        - {{ include "safe.transaction_service.create_db_container" . | nindent 10 }}
      containers:
        - name: django
          image: {{ .Values.transaction_service.image.name }}:{{ .Values.transaction_service.image.tag }}
          command: [bash]
          args:
            - -c
            - |
              {{ .Files.Get "files/transaction-service/web/run_web.sh" | nindent 14 }}
          env:
            {{ include "safe.transaction_service.common_env" . | nindent 12 }}
          resources:
            requests:
              cpu: 200m
              memory: 900Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - name: staticfiles
              mountPath: /nginx
            - name: gunicorn
              mountPath: /gunicorn

        - name: nginx
          image: nginx:stable-alpine3.17
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DOCKER_NGINX_VOLUME_ROOT
              value: /www
            - name: GUNICORN_BIND_SOCKET
              value: unix:/gunicorn/gunicorn.socket
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: staticfiles
              mountPath: /nginx
            - name: gunicorn
              mountPath: /gunicorn
          readinessProbe:
            httpGet:
              path: /api/v1/about/
              port: http
            initialDelaySeconds: 15
      volumes:
        - name: nginx-config
          configMap:
            name: transaction-web-nginx
        - name: staticfiles
          emptyDir: {}
        - name: gunicorn
          emptyDir: {}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-web-nginx
  labels:
    app: transaction-web
data:
  nginx.conf: |-
    {{ .Files.Get "files/transaction-service/nginx/nginx.conf" | nindent 4 }}


---
apiVersion: v1
kind: Secret
metadata:
  name: transaction-service
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "transaction-service") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secret-key") | default (randAlphaNum 128 | b64enc) }}
  secret-key: {{ $secretKey | quote }}
  {{- $djangoSuperuserPassword := (get $secretData "django-superuser-password") | default (randAlphaNum 32 | b64enc) }}
  django-superuser-password: {{ $djangoSuperuserPassword | quote }}
